### ISSUE TITLE
Code for reconstructing images from augmented samples in feature space

### ISSUE THREAD

**Issue by mhk257** [blackfeather-wang/ISDA-for-Deep-Networks#11]
Your idea of implicit and efficient feature space augmentation is very nice and a valuable contribution.
It would be great if you can please share the code for reconstructing images from augmented samples in feature space?

**Comment by blackfeather-wang** [comment]
Thank you for your attention!

We are now working on that. We will update the code as soon as we can. 😁

**Comment by mhk257** [comment]
Hi, can you please share the uncleaned code for reconstructing images?

**Comment by ahmadmughees** [comment]
Hi @blackfeather-wang,

I am also looking for the same task explained in Appendix E. If you dont have cleaned code right now, I am all good for raw code as well. 

Looking forward to your response.
Thanks alot.

**Comment by blackfeather-wang** [comment]
We have updated the code for visualizing deep features! Please check the code. If you have any question, please feel free to reach me.
