### ISSUE TITLE
Implementation of the new loss

### ISSUE THREAD

**Issue by chaoyan1037** [blackfeather-wang/ISDA-for-Deep-Networks#12]
Thanks for sharing your implementation! I have a question about the implementation, how does the [ISDA loss implementation](https://github.com/blackfeather-wang/ISDA-for-Deep-Networks/blob/master/Image%20classification%20on%20CIFAR/ISDA.py#L112) relate to the formula 10 in the TPAMI paper? Could you please explain more about the implementation? Thanks a lot!

**Comment by blackfeather-wang** [comment]
Thank you for your attention.

In fact, this implementation follows Eq. (7) of the paper. 😁

**Comment by chaoyan1037** [comment]
I see. Brilliant, thanks for the reminder!
