### ISSUE TITLE
About the covariance matrix

### ISSUE THREAD

**Issue by peterzpy** [blackfeather-wang/ISDA-for-Deep-Networks#14]
It seems that you only use the diagonal elements of the covariance matrix. I wonder why not use the complete matrix to augment the feature? Looking forward to your reply.

**Comment by blackfeather-wang** [comment]
Thank you for your attention.

I guess you see this in our code for imagenet & segmentation. As we state in the paper, we approximate the covariance matrices by their diagonals (see sec. 6.1) to save GPU memory (reduce the covariance tensor from 1000x2048x2048 to 1000x2048). You may check our code on cifar for the Vanilla ISDA.

**Comment by peterzpy** [comment]
Thanks for your reply. I have no more questions and you could close this issue. : )
