### ISSUE TITLE
Is it applicable to one stage object detectors(yolo)?

### ISSUE THREAD

**Issue by cszer** [blackfeather-wang/ISDA-for-Deep-Networks#19]
In yolov3 or v4 authors use bce loss for classification , is ISDA applicable to this kind of prediction?

**Comment by blackfeather-wang** [comment]
Thank you for your attention. Indeed, ISDA can be easily applied to any deep network with soft-max CE loss. We believe that it can also be used in YOLO. However, as we have not conducted experiments on YOLO now, it may be hard to estimate the improvements from ISDA.
