### ISSUE TITLE
long-tailed problem

### ISSUE THREAD

**Issue by AaboutL** [blackfeather-wang/ISDA-for-Deep-Networks#20]
你好，
谢谢你的分享。我有一个问题，这个增强方法对于long-tailed problem是否work，或者说，如果很多类别中的样本仅仅只有极少的几张图片，这个方法能起作用吗？

**Comment by blackfeather-wang** [comment]
您好，

非常感谢您的关注，事实上long-tailed problem + ISDA也是我们正在关注的问题，我们刚刚完成了一项工作，发表在cvpr2021，已经挂到Arxiv上面: MetaSAug: Meta Semantic Augmentation for Long-Tailed Visual Recognition。

根据我们目前的结果，ISDA直接应用于long-tailed problem 是可以改善表现的，只不过其效果可能比较有限，主要原因是对于样本较少的类别协方差矩阵估计的不大好，因此是需要一定的改进的。
