### ISSUE TITLE
Can you share the code of Appendix C if convenient

### ISSUE THREAD

**Issue by zhangzj2114** [blackfeather-wang/ISDA-for-Deep-Networks#3]
I'm new to CV, and I learned a lot from your work.  Can you share the code of Appendix C if convenient? Thank you.

**Comment by dariocazzani** [comment]
I'd like to see the code for Appendix C as well if possible.
Thank you

**Comment by blackfeather-wang** [comment]
We are working on the camera-ready version of the code. If you do not care, please send an e-mail to me (Yulin Wang) to acquire a rough version.
