### ISSUE TITLE
Questions about ISDA for ImageNet

### ISSUE THREAD

**Issue by JamenceTom** [blackfeather-wang/ISDA-for-Deep-Networks#32]
Thank you for your great work!!!
Sorry to bother you, I am confused on the implementation of ISDA for ImageNet, as shown in the following image.
![image](https://user-images.githubusercontent.com/55536181/146707362-0c70693e-0742-44ca-944f-3a39defeb86d.png)
Why do you only consider the diagonal elements of sigma2?

**Comment by jackliu333** [comment]
It could be this implementation ignores the covariance between deep features.

**Comment by blackfeather-wang** [comment]
Indeed, we ignore the covariance between deep features on ImageNet (only ImageNet) to save the GPU memory. Take ResNet-50 for example. If we consider all the covariance, we will have a 1000 * 2048 * 2048 tensor, while in the current implementation, we only need to process a 1000 * 2048 tensor. We find that ISDA significantly improves the accuracy even with this implementation technique.
