### ISSUE TITLE
Performance improvements on ImageNet

### ISSUE THREAD

**Issue by JamesHao-ml** [blackfeather-wang/ISDA-for-Deep-Networks#4]
I found that you update the Arxiv paper on Aril 25 and the performance on ImageNet is largely improved, from 0.28% gain to 1.1% gain on ResNet-50. Is there any special change that leads to the larger improvements? Thanks.

**Comment by blackfeather-wang** [comment]
Thank you for the question.

**Comment by blackfeather-wang** [comment]
Thank you for your question. In the original conference version, we train ResNet-50 for 120 epochs with a step lr schedule (*0.1 at 30, 60, 90 epoch). The new results use a longer schedule with 300 epochs and a cosine lr schedule, following other sota augmentation techniques. We find that these regularization techniques generally tend to be more effective with longer training time.

**Comment by JamesHao-ml** [comment]
Thanks!
