### ISSUE TITLE
If fc can only be nn.Linear rather nn.Conv2d? 

### ISSUE THREAD

**Issue by xiong224** [blackfeather-wang/ISDA-for-Deep-Networks#9]

**Comment by blackfeather-wang** [comment]
Thank you for your attention.
It can be nn.Conv2d, but some reshape operations may be essential. Please refer to our segmentation code for details.

**Comment by xiong224** [comment]
Thanks very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blackfeather-wang/ISDA-for-Deep-Networks"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 晚上10:53
收件人:&nbsp;"blackfeather-wang/ISDA-for-Deep-Networks"<ISDA-for-Deep-Networks@noreply.github.com&gt;;
抄送:&nbsp;"熊晏民"<895917144@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [blackfeather-wang/ISDA-for-Deep-Networks] If fc can only be nn.Linear rather nn.Conv2d?  (#9)





 
Thank you for your attention.
 It can be nn.Conv2d, but some reshape operations may be essential. Please refer to our segmentation code for details.
